[package]
name = "orx-concurrent-iter"
version = "1.17.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "A thread-safe, ergonomic and lightweight concurrent iterator trait and efficient implementations."
license = "MIT"
repository = "https://github.com/orxfun/orx-concurrent-iter/"
keywords = ["concurrency", "iterator", "iteration", "atomic", "parallelism"]
categories = ["data-structures", "concurrency", "rust-patterns"]

[dependencies]
orx-pinned-vec = "2.11"

[dev-dependencies]
orx-concurrent-bag = "1.14"
orx-fixed-vec = "2.11"
orx-pinned-concurrent-col = "1.4"
orx-split-vec = "2.13"
test-case = "3.3.1"
