[package]
name = "orx-concurrent-iter"
version = "1.25.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "A thread-safe, ergonomic and lightweight concurrent iterator trait and efficient implementations."
license = "MIT"
repository = "https://github.com/orxfun/orx-concurrent-iter/"
keywords = ["concurrency", "iterator", "iteration", "atomic", "parallelism"]
categories = ["data-structures", "concurrency", "rust-patterns"]

[dependencies]

[dev-dependencies]
orx-pinned-vec = "3.7"
orx-fixed-vec = "3.7"
orx-split-vec = "3.7"
orx-pinned-concurrent-col = "2.6"
orx-concurrent-bag = "2.6"
test-case = "3.3.1"
